rvm:
- 2.0.0
before_script:
- sh -c 'cp config/database.yml.example config/database.yml'
- sh -c 'bundle exec rake db:migrate'
- sh -c 'bundle exec rake db:test:prepare'
cache: bundler
env:
  global:
  - secure: Po/FaFWyyZhC52nFSO4pq/O+PNO1rzXDs87ORdd761lS91GPTkwT7TncnGT5DetxKw04qi7eL2NTFgS2sWfzFulOxFAbSAavEqQgV/9ZosnznOdt7dlPvYwr/wrmgG3ML+4z1AaBKOdUNWQa/CPL4jWnf+VuEV6G8psuZSv7Orc=
