rvm: 2.0.0-p247
before_script:
- sh -c 'cp config/database.yml.example config/database.yml'
- sh -c 'bundle exec rake db:migrate'
- sh -c 'bundle exec rake db:test:prepare'
cache: bundler
env:
  global:
    secure: fQuJhdgLnV2TNz9TY09p4ro1gC6ggCH14QrV6cnyOhOnu+1w5ykTYVQ0nuTNqxSejohwF1dSdXW+HOO6UTEh+BHlxn6sZZMZ54OkYZyeMIB5UxPrRnkzepMM3vUmlicwDr1qG2VFr078w3rQ8PVW5PS690gsh7q55ldXjDSpXjA=
